"""Aggregate the audited 4x4 shared-pool studies without cross-backend timing claims.

The ACE adaptive, ACE compiler, and native SeQUeNCe studies share the same
hash-locked trace, seeds, and memory contract.  Their latency boundaries and
physical implementations differ, so paired effects are deliberately computed
only within one backend.
"""

from __future__ import annotations

import argparse
import json
from collections import defaultdict
from pathlib import Path

from experiment_statistics import summarize


def load(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def stat(rows: list[dict], field: str) -> dict:
    return summarize([row[field] for row in rows if row.get(field) is not None])


def fmt(value: float | None, digits: int = 4, percent: bool = False) -> str:
    if value is None:
        return "—"
    result = f"{value:.{digits}f}"
    return result + "%" if percent else result


def latency_effect(candidate: list[dict], baseline: list[dict]) -> dict:
    candidate_by_seed = {row["seed"]: row for row in candidate}
    baseline_by_seed = {row["seed"]: row for row in baseline}
    if set(candidate_by_seed) != set(baseline_by_seed):
        raise ValueError("candidate and baseline seed sets differ")
    reductions = [
        100 * (baseline_by_seed[seed]["latency_ms"] - candidate_by_seed[seed]["latency_ms"])
        / baseline_by_seed[seed]["latency_ms"]
        for seed in sorted(candidate_by_seed)
    ]
    return summarize(reductions)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--ace-adaptive", required=True, type=Path)
    parser.add_argument("--ace-compiler", required=True, type=Path)
    parser.add_argument("--native-study", required=True, type=Path)
    parser.add_argument("--output", required=True, type=Path)
    args = parser.parse_args()

    ace_adaptive = load(args.ace_adaptive)
    ace_compiler = load(args.ace_compiler)
    native = load(args.native_study)
    if native.get("status") != "complete":
        raise ValueError("native study is not complete")

    groups: dict[str, list[dict]] = defaultdict(list)
    for run in ace_adaptive["runs"]:
        row = run["summary"]
        groups[f"ACE:{row['strategy']}"] .append({
            "seed": int(row["seed"]),
            "latency_ms": row["average_request_latency_ms"],
            "ready_rate": None,
            "delivered_fidelity": row["average_delivered_epr_fidelity"],
            "prepared_fidelity": row["adaptive_fidelity_at_use"],
            "expiry_percent": row["adaptive_expiry_percentage"],
            "fallback_rate": None if row["strategy"] == "odg" else None,
            "generated_pairs": row["adaptive_generated_pairs"],
            "used_pairs": row["adaptive_utilized_pairs"],
        })
    for run in ace_compiler["runs"]:
        row = run["summary"]
        strategy = "odg" if row["strategy"] == "matched-on-demand" else row["strategy"]
        # The ODG row is intentionally identical to ACE adaptive ODG; retain one copy.
        if strategy == "odg":
            continue
        groups[f"ACE:{strategy}"] .append({
            "seed": int(row["seed"]),
            "latency_ms": row["average_request_latency_ms"],
            "ready_rate": row["pregenerated_success_rate"],
            "delivered_fidelity": row["average_delivered_epr_fidelity"],
            "prepared_fidelity": row["average_compiler_fidelity_at_utilization"],
            "expiry_percent": row["compiler_expiry_percentage"],
            "fallback_rate": row["on_demand_fallback_rate"],
            "generated_pairs": row["generated_compiler_pairs"],
            "used_pairs": row["utilized_compiler_pairs"],
        })
    for row in native["trials"]:
        strategy = "odg" if row["strategy"] == "matched-odg" else row["strategy"]
        groups[f"native:{strategy}"].append({
            "seed": int(row["seed"]),
            "latency_ms": row["average_latency_ms"],
            "ready_rate": row["pregenerated_transfer_success_rate"],
            "delivered_fidelity": row["average_epr_fidelity_at_teleportation"],
            "prepared_fidelity": row["average_compiler_epr_fidelity_at_utilization"],
            "expiry_percent": row["expiry_percentage"],
            "fallback_rate": row["compiler_on_demand_fallbacks"] / row["requests"],
            "generated_pairs": row["compiler_successful_preparations"],
            "used_pairs": row["compiler_adopted_attempts"],
        })

    expected = set(range(30))
    for name, rows in groups.items():
        if {row["seed"] for row in rows} != expected:
            raise ValueError(f"{name}: expected seeds 0..29")

    lines = [
        "# Audited shared-pool 4x4 QFT results", "",
        "Generated by `summarize_shared_pool_study.py` from the three completed "
        "30-seed artifacts. Every row has 4,954 requests per seed (148,620 per policy). "
        "All trials completed successfully.", "",
        "> **Interpretation boundary.** The workload, trace ordering, seeds, four-memory "
        "shared pool, compiler/autonomous cap of three, and demand-first admission rule are "
        "matched. ACE and native SeQUeNCe nevertheless use different physical implementations "
        "and latency boundaries. Absolute milliseconds are therefore shown for reproducibility, "
        "but only paired comparisons *within one backend* are scientific comparisons.", "",
        "## Aggregate policy metrics", "",
        "`Ready` is the fraction of requests supplied by an intended prepared pair. "
        "`Prepared fidelity@use` applies only to such prepared pairs; `delivered fidelity` "
        "covers all successful requests, including fallback/on-demand delivery.", "",
        "| Backend | Policy | Mean latency (ms) [95% CI] | Ready | Delivered fidelity | Prepared fidelity@use | Expiry | Fallback |", 
        "|---|---|---:|---:|---:|---:|---:|---:|",
    ]
    ordered = ("ACE:odg", "ACE:cgp", "ACE:acgp", "ACE:fixed", "ACE:dynamic",
               "native:odg", "native:fixed", "native:dynamic")
    for name in ordered:
        rows = groups[name]
        latency = stat(rows, "latency_ms")
        ready = stat(rows, "ready_rate")
        delivered = stat(rows, "delivered_fidelity")
        prepared = stat(rows, "prepared_fidelity")
        expiry = stat(rows, "expiry_percent")
        fallback = stat(rows, "fallback_rate")
        backend, policy = name.split(":")
        lines.append(
            f"| {backend} | {policy.upper()} | "
            f"{fmt(latency['mean'], 6)} [{fmt(latency['ci95_low'], 6)}, {fmt(latency['ci95_high'], 6)}] | "
            f"{fmt(ready['mean'] * 100 if ready['mean'] is not None else None, 2, True)} | "
            f"{fmt(delivered['mean'])} | {fmt(prepared['mean'])} | "
            f"{fmt(expiry['mean'], 2, True)} | "
            f"{fmt(fallback['mean'] * 100 if fallback['mean'] is not None else None, 2, True)} |"
        )

    effects = [
        ("ACE", "cgp", "odg"), ("ACE", "acgp", "odg"),
        ("ACE", "fixed", "odg"), ("ACE", "dynamic", "odg"),
        ("ACE", "fixed", "cgp"), ("ACE", "dynamic", "cgp"),
        ("ACE", "fixed", "acgp"), ("ACE", "dynamic", "acgp"),
        ("ACE", "dynamic", "fixed"),
        ("native", "fixed", "odg"), ("native", "dynamic", "odg"),
        ("native", "dynamic", "fixed"),
    ]
    lines += ["", "## Seed-paired latency effects", "",
              "Positive means the candidate is faster. Confidence intervals are two-sided "
              "Student-t 95% intervals over the same 30 seeds.", "",
              "| Backend | Candidate vs baseline | Mean reduction | 95% CI |", "|---|---|---:|---:|"]
    for backend, candidate, baseline in effects:
        result = latency_effect(groups[f"{backend}:{candidate}"], groups[f"{backend}:{baseline}"])
        lines.append(
            f"| {backend} | {candidate.upper()} vs {baseline.upper()} | "
            f"{fmt(result['mean'], 2, True)} | "
            f"[{fmt(result['ci95_low'], 2)}, {fmt(result['ci95_high'], 2)}]% |"
        )

    lines += [
        "", "## Reproducibility and audit evidence", "",
        "- Trace: `qft_requests.txt`, SHA-256 "
        "`61d97492195aea40fad48d5bc4e1b48b2dd019eea20fe24aada8c954e3073da1`.",
        "- ACE compiler audit: 90 trials, 445,860 request instances, 193,741 compiler-pair records; passed.",
        "- ACE ODG/CGP/ACGP audit: 90 trials, 445,860 request instances, 21,226 adaptive-pair records; passed.",
        "- Native audit: 90 trials, 445,860 successful requests and zero failures; pair accounting, "
        "no double use, memory bounds, timing stages, and fidelity bounds passed.",
        "- Source outputs are intentionally ignored because the per-request traces are large. "
        "Their paths and audit commands are recorded in `ADAPTIVE_BASELINE_SPEC.md` and "
        "`results/SHARED_POOL_COMPILER_30SEED.md`.",
        "",
    ]
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {args.output}")


if __name__ == "__main__":
    main()
